import re
def replace(address):
    new_address= address
    new_address=re.sub(r"\sDB\b",' DUBLIN',new_address)
    new_address=re.sub(r"\sDL\b",' DUBLIN',new_address)
    new_address=re.sub(r"\sDUBLN\b",' DUBLIN',new_address)
    new_address=re.sub(r"\sDUBIN\b",' DUBLIN',new_address)
    new_address=re.sub(r"\b6\sW\b",'6W',new_address)
    new_address=re.sub(r"\b6\sWEST\b",'6W',new_address)
    new_address=re.sub(r"\bWICLOW\b",'WICKLOW',new_address)
    new_address=re.sub(r"\sKK\b",' KILKENNY',new_address)
    new_address=re.sub(r"\sCK\b",' CORK',new_address)
    new_address=re.sub(r"\sGW\b",' GALWAY',new_address)
    new_address=re.sub(r"\sKE\b",' KILDARE',new_address)
    new_address=re.sub(r"\sKY\b",' KERRY',new_address)
    new_address=re.sub(r"\sMO\b",' MAYO',new_address)
    new_address=re.sub(r"\sCE\b",' CLARE',new_address)
    new_address=re.sub(r"\sDN\b",' DOWN',new_address)
    new_address=re.sub(r"\sWX\b",' WEXFORD',new_address)
    new_address=re.sub(r"\sLK\b",' LIMERICK',new_address)
    new_address=re.sub(r"\sLM\b",' LEITRIM',new_address)
    new_address=re.sub(r"\sLS\b",' LAOIS',new_address)
    new_address=re.sub(r"\sOY\b",' OFFALY',new_address)
    new_address=re.sub(r"\sMN\b",' MONAGHAN',new_address)
    new_address=re.sub(r"\sLH\b",' LOUTH',new_address)
    new_address=re.sub(r"\sMH\b",' MEATH',new_address)
    new_address=re.sub(r"\sCN\b",' CAVAN',new_address)
    new_address=re.sub(r"\sCW\b",' CARLOW',new_address)
    new_address=re.sub(r"\sWW\b",' WICKLOW',new_address)
    new_address=re.sub(r"\sWD\b",' WATERFORD',new_address)
    new_address=re.sub(r"\sLD\b",' LONGFORD',new_address)
    new_address=re.sub(r"\sSO\b",' SLIGO',new_address)
    new_address=re.sub(r"\sWH\b",' WESTMEATH',new_address)
    new_address=re.sub(r"\sAM\b",' ANTRIM',new_address)
    new_address=re.sub(r"\sRN\b",' ROSCOMMON',new_address)
    new_address=re.sub(r"\sTE\b",' TYRONE',new_address)
    new_address=re.sub(r"\sTP\b",' TIPPERARY',new_address)
    new_address=re.sub(r"\sDE\b",' DERRY',new_address)
    new_address=re.sub(r"\sCO\b",' COUNTY',new_address)
    new_address=re.sub(r"\sCOUNTY\b",'',new_address)

    return new_address